services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - elo-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - elo-network

networks:
  elo-network:
    driver: bridge
